### ISSUE TITLE
Please update per latest vitasdk, libvita2d, libftpvita...

### ISSUE THREAD

**Issue by littlebalup** [zecoxao/PSDK3v3#1]
In order to be able to compil latest Vitashell.... please!!

**Comment by zecoxao** [comment]
sure thing :)

**Comment by littlebalup** [comment]
Thanks :)
Meantime I forked, updated and added some stuff to be able to compil vitashell.

**Comment by zecoxao** [comment]
i use builds.
updated.
can i close the issue?

**Comment by littlebalup** [comment]
Yes of course. i'm doing it for you. thanks.
